

### Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Данные

In [2]:
df = pd.read_csv("AMES_Final_DF.csv")

In [3]:
df.head()

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,441.0,...,0,0,0,0,1,0,0,0,1,0
1,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,...,0,0,0,0,1,0,0,0,1,0
2,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,...,0,0,0,0,1,0,0,0,1,0
3,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,1045.0,...,0,0,0,0,1,0,0,0,1,0
4,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,...,0,0,0,0,1,0,0,0,1,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Columns: 274 entries, Lot Frontage to Sale Condition_Partial
dtypes: float64(11), int64(263)
memory usage: 6.1 MB

**ЗАДАНИЕ: Мы будем пытаться спрогнозировать значение колонки SalePrice. Разделите данные на две части - признаки X и целевая переменная y.**

In [5]:
df[['Lot Frontage', 'SalePrice']].head()

   Lot Frontage  SalePrice
0         141.0     215000
1          80.0     105000
2          81.0     172000
3          93.0     244000
4          74.0     189900

In [6]:
X = df.drop('SalePrice', axis = 1)
X

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,141.000000,31770,6,5,1960,1960,112.0,639.0,0.0,441.0,...,0,0,0,0,1,0,0,0,1,0
1,80.000000,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,...,0,0,0,0,1,0,0,0,1,0
2,81.000000,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,...,0,0,0,0,1,0,0,0,1,0
3,93.000000,11160,7,5,1968,1968,0.0,1065.0,0.0,1045.0,...,0,0,0,0,1,0,0,0,1,0
4,74.000000,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,37.000000,7937,6,6,1984,1984,0.0,819.0,0.0,184.0,...,0,0,0,0,1,0,0,0,1,0
2921,75.144444,8885,5,5,1983,1983,0.0,301.0,324.0,239.0,...,0,0,0,0,1,0,0,0,1,0
2922,62.000000,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,...,0,0,0,0,1,0,0,0,1,0
2923,77.000000,10010,5,5,1974,1975,0.0,1071.0,123.0,195.0,...,0,0,0,0,1,0,0,0,1,0
2924,74.000000,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,...,0,0,0,0,1,0,0,0,1,0

In [7]:
y = df['SalePrice']
y

0       215000
1       105000
2       172000
3       244000
4       189900
         ...
2920    142500
2921    131000
2922    132000
2923    170000
2924    188000
Name: SalePrice, Length: 2925, dtype: int64

**ЗАДАНИЕ: С помощью scikit-learn разделите и X, и y на обучающий и тестовый наборы данных. Поскольку далее мы будем использовать поиск по сетке, то выделите под тестовые данные 10% от всех данных. Чтобы получить такое же разбиение данных, как и в нашем блокноте, можете использовать random_state = 101.**

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

**ЗАДАНИЕ: Признаки в этом наборе данных имеют различный масштаб и различные единицы измерения. Для оптимальной работы регрессии, выполните масштабирование признаков X. Обратите внимание на то, какие данные подавать на вход для .fit(), а какие данные на вход для .transform().**

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[-0.8384808 , -0.50803335, -0.05639001, ..., -0.13038998,
         0.46443986, -0.30126134],
       [-1.03015138, -0.50803335,  1.35711957, ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 1.26989557,  0.06576361,  0.65036478, ..., -0.13038998,
         0.46443986, -0.30126134],
       ...,
       [-0.45513964, -0.42320424, -0.05639001, ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.07195445, -0.42000314, -0.7631448 , ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.0880722 ,  0.30477899,  1.35711957, ..., -0.13038998,
         0.46443986, -0.30126134]])

In [12]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.24211099, -0.51696976, -0.7631448 , ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.79071912,  0.43175591,  2.06387436, ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.5511309 ,  0.04829094, -0.7631448 , ..., -0.13038998,
        -2.15313128,  3.31937718],
       ...,
       [ 1.46156615,  0.74066194,  0.65036478, ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.93447206,  0.42215261,  2.06387436, ..., -0.13038998,
         0.46443986, -0.30126134],
       [ 0.02403681, -0.17338515,  0.65036478, ..., -0.13038998,
         0.46443986, -0.30126134]])

**ЗАДАНИЕ: Мы будем использовать модель "Elastic Net". Создайте экземпляр модели ElasticNet в scikit-learn, используя параметры по умолчанию.**

In [13]:
from sklearn.linear_model import ElasticNet

In [14]:
model = ElasticNet()

**ЗАДАНИЕ: Модель Elastic Net работает с двумя основными параметрами - alpha и L1_ratio. Создайте словарь с набором различных значений этих параметров, для поиска по сетке. Вы можете выбрать различные значения параметров, но имейте ввиду, что Ваши результаты могут не совпасть с результатами в блокноте с решениями.**

In [15]:
params = {'alpha': [1, 50, 100], 'l1_ratio':[0.1, 0.5, 1.0]}

**ЗАДАНИЕ: С помощью scikit-learn создайте объект GridSearchCV и запустите поиск по сетке для нахождения наилучших параметров модели, используя обучающие данные (предварительно смасштабированные). [Для некоторых комбинаций параметров Вы можете получить предупреждения (warnings).](https://stackoverflow.com/questions/20681864/lasso-on-sklearn-does-not-converge)**

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
grid_model = GridSearchCV(estimator = model,
                          param_grid = params, 
                          scoring = 'neg_mean_squared_error',
                          cv = 5, 
                          verbose = 1)
grid_model.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

/Users/egor/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.025e+11, tolerance: 1.355e+09
  model = cd_fast.enet_coordinate_descent(
/Users/egor/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.127e+11, tolerance: 1.308e+09
  model = cd_fast.enet_coordinate_descent(
/Users/egor/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.475e+11, tolerance: 1.415e+09
  model = cd_fast.enet_coordinate_descent(
/Users/egor/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.526e+11, tolerance: 1.438e+09
  model = cd_fast.enet_coordinate_descent(
/Users/egor/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.559e+11, tolerance: 1.346e+09
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [1, 50, 100], 'l1_ratio': [0.1, 0.5, 1.0]},
             scoring='neg_mean_squared_error', verbose=1)

**ЗАДАНИЕ: Оцените работу модели на тестовом наборе данных (предварительно смасштабированном) в 10%, которые модель ещё не видела. В блокноте с решениями мы получили MAE = $\$$14149 и RMSE = $\$$20532**

In [18]:
y_pred = grid_model.predict(X_test)

In [19]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

In [20]:
mean_absolute_error(y_test, y_pred)

14195.354900562172

In [21]:
root_mean_squared_error(y_test, y_pred)

20558.50856689317

## Отличная работа!!!

----